[package]
name = "quantization"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.4"
permutation_iterator = "0.1.2"
rand = "0.8.5"

[dependencies]
serde = { version = "~1.0", features = ["derive", "rc"] }

[[bench]]
name = "encode"
harness = false
